server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: identity
              uri: lb://identity
              predicates:
                - Path=/auth/**

            # - id: operators-admin
            #   uri: lb://operator-service
            #   predicates:
            #     - Path=/operators/**

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:keys/public.pem