server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_identity
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  public-key-location: classpath:keys/public.pem
  private-key-location: classpath:keys/private.pem
  expiration: 900000
  refresh-expiration: 604800000